name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push BankWebhook image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.bankWebhook
          push: true
          tags: l0nw0lf/bankWebhook:latest

      - name: Verify Pushed Image
        run: docker pull l0nw0lf/bankWebhook:latest

      - name: Build and Push MockBank image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.mockBank
          push: true
          tags: l0nw0lf/mockBank:latest

      - name: Verify Pushed Image
        run: docker pull l0nw0lf/mockBank:latest

      - name: Build and Push UserApp image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.userApp
          push: true
          tags: l0nw0lf/userApp:latest

      - name: Verify Pushed Image
        run: docker pull l0nw0lf/userApp:latest
