name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      #- name: Build and Push BankWebhook image
      #uses: docker/build-push-action@v2
      #with:
      #context: .
      #file: ./docker/Dockerfile.bankWebhook
      #push: true
      #tags: l0nw0lf/bank-webhook:latest

      #- name: Verify Pushed Image
      #run: docker pull l0nw0lf/bank-webhook:latest

      #- name: Build and Push MockBank image
      #uses: docker/build-push-action@v2
      #with:
      #context: .
      #file: ./docker/Dockerfile.mockBank
      #push: true
      #tags: l0nw0lf/mock-bank:latest

      #- name: Verify Pushed Image
      #run: docker pull l0nw0lf/mock-bank:latest

      - name: Build and Push UserApp image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.userApp
          push: true
          tags: l0nw0lf/user-app:latest

      - name: Verify Pushed Image
        run: docker pull l0nw0lf/user-app:latest

      - name: Set up SSH private key
        run: echo "$PRIVATE_KEY" > key.pem && chmod 700 key.pem
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}

      - name: SSH into EC2 instance
        run: |
          ssh -i key.pem ${{secrets.SSH_USERNAME}}@${{secrets.SSH_USERNAME}} 
          sudo docker pull l0nw0lf/user-app:latest
          sudo docker stop user-app || true
          sudo docker rm user-app || true
          sudo docker run -d --name user-app -p 3005:3000 l0nw0lf/user-app:latest
